services:
  eschalt_db:
    restart: no
    
  sass:
    image: node:22-alpine
    working_dir: /app
    restart: no
    volumes:
      - ./eSchalt/Frontend/Scss:/app/Frontend/Scss
      - ./eSchalt/wwwroot/css:/app/wwwroot/css
      - ./eSchalt/wwwroot/webfonts:/app/wwwroot/webfonts
      - ./eSchalt/package.json:/app/package.json
      - ./eSchalt/package-lock.json:/app/package-lock.json
    command: sh -c "npm install && npm run copy:fa && npm run sass:watch"

#  eschalt_cache:
#    restart: no