services:
  eschalt_db:
    image: postgres:latest
    container_name: eschalt_db
    restart: always
    environment:
      - POSTGRES_DB=eschalt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - eschalt_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
        
        #  eschalt_cache:
        #    image: redis:latest
        #    restart: always
        #    ports:
        #      - "6379:6379"

volumes:
  eschalt_db:
    