services:
  eschalt:
    restart: no
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      dockerfile: eSchalt/Docker/Dev.Dockerfile
      args:
        BUILD_CONFIGURATION: "Debug"
    volumes:
      - ./eSchalt/Frontend/Scss:/app/Frontend/Scss
      - ./eSchalt/Pages:/app/Pages
      
  eschalt_db:
    restart: no
    
  eschalt_cache:
    restart: no
  
  eschalt_proxy:
    restart: no