services:
  eschalt_db:
    restart: no
    
  sass:
    image: node:22-alpine
    working_dir: /app
    restart: no
    volumes:
      - ./eSchalt/Frontend/Scss:/app/Frontend/Scss
      - ./eSchalt/wwwroot/css:/app/wwwroot/css
      - ./eSchalt/package.json:/app/package.json
      - ./eSchalt/node_modules:/app/node_modules
    command: sh -c "npm install && npm run sass:watch"

#  eschalt_cache:
#    restart: no