// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eSchalt.Backend;

#nullable disable

namespace eSchalt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eSchalt.Backend.Models.Eschalttabledemo", b =>
                {
                    b.Property<string>("Ausgang")
                        .HasColumnType("text")
                        .HasColumnName("ausgang");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text")
                        .HasColumnName("bemerkung");

                    b.Property<string>("Beschr")
                        .HasColumnType("text")
                        .HasColumnName("Beschr. ");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("integer")
                        .HasColumnName("componentid");

                    b.Property<string>("Dimmer")
                        .HasColumnType("text")
                        .HasColumnName("dimmer");

                    b.Property<string>("Eingang")
                        .HasColumnType("text")
                        .HasColumnName("eingang");

                    b.Property<string>("Fi")
                        .HasColumnType("text")
                        .HasColumnName("fi");

                    b.Property<string>("Gruppe")
                        .HasColumnType("text")
                        .HasColumnName("gruppe");

                    b.Property<string>("Info")
                        .HasColumnType("text")
                        .HasColumnName("Info ");

                    b.Property<string>("KabelInfo")
                        .HasColumnType("text")
                        .HasColumnName("Kabel Info");

                    b.Property<string>("Leiter")
                        .HasColumnType("text")
                        .HasColumnName("leiter");

                    b.Property<string>("Raum")
                        .HasColumnType("text")
                        .HasColumnName("raum");

                    b.Property<string>("Relais")
                        .HasColumnType("text")
                        .HasColumnName("relais");

                    b.Property<string>("Sicherung")
                        .HasColumnType("text")
                        .HasColumnName("sicherung");

                    b.Property<string>("SpsPositionImArray")
                        .HasColumnType("text")
                        .HasColumnName("SPS Position im array");

                    b.Property<string>("Stockwerk")
                        .HasColumnType("text")
                        .HasColumnName("stockwerk");

                    b.Property<string>("StockwerkKurz")
                        .HasColumnType("text")
                        .HasColumnName("Stockwerk(kurz)");

                    b.Property<string>("Typ")
                        .HasColumnType("text")
                        .HasColumnName("typ");

                    b.ToTable("eschaltdemo", (string)null);
                });

            modelBuilder.Entity("eSchalt.Backend.Models.HardcodingDbTest", b =>
                {
                    b.Property<int?>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("componentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("ComponentId"));

                    b.Property<string>("Ausgang")
                        .HasColumnType("text")
                        .HasColumnName("ausgang");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text")
                        .HasColumnName("bemerkung");

                    b.Property<string>("Beschr")
                        .HasColumnType("text")
                        .HasColumnName("Beschr. ");

                    b.Property<string>("Dimmer")
                        .HasColumnType("text")
                        .HasColumnName("dimmer");

                    b.Property<string>("Eingang")
                        .HasColumnType("text")
                        .HasColumnName("eingang");

                    b.Property<string>("Fi")
                        .HasColumnType("text")
                        .HasColumnName("fi");

                    b.Property<string>("Gruppe")
                        .HasColumnType("text")
                        .HasColumnName("gruppe");

                    b.Property<string>("Info")
                        .HasColumnType("text")
                        .HasColumnName("Info ");

                    b.Property<string>("KabelInfo")
                        .HasColumnType("text")
                        .HasColumnName("Kabel Info");

                    b.Property<string>("Leiter")
                        .HasColumnType("text")
                        .HasColumnName("leiter");

                    b.Property<string>("Raum")
                        .HasColumnType("text")
                        .HasColumnName("raum");

                    b.Property<string>("Relais")
                        .HasColumnType("text")
                        .HasColumnName("relais");

                    b.Property<string>("Sicherung")
                        .HasColumnType("text")
                        .HasColumnName("sicherung");

                    b.Property<string>("SpsPositionImArray")
                        .HasColumnType("text")
                        .HasColumnName("SPS Position im array");

                    b.Property<string>("Stockwerk")
                        .HasColumnType("text")
                        .HasColumnName("stockwerk");

                    b.Property<string>("StockwerkKurz")
                        .HasColumnType("text")
                        .HasColumnName("Stockwerk(kurz)");

                    b.Property<string>("Typ")
                        .HasColumnType("text")
                        .HasColumnName("typ");

                    b.HasKey("ComponentId");

                    b.ToTable("hardcodingdbtest", (string)null);

                    b.HasData(
                        new
                        {
                            ComponentId = 1,
                            Ausgang = "A1",
                            Bemerkung = "Remark 1",
                            Beschr = "Description 1",
                            Dimmer = "D1",
                            Eingang = "I1",
                            Fi = "FI-A",
                            Gruppe = "G1",
                            Info = "Info 1",
                            KabelInfo = "Copper",
                            Leiter = "L1",
                            Raum = "101",
                            Relais = "R1",
                            Sicherung = "S1",
                            SpsPositionImArray = "1",
                            Stockwerk = "First Floor",
                            StockwerkKurz = "FF",
                            Typ = "Type A"
                        },
                        new
                        {
                            ComponentId = 2,
                            Ausgang = "A2",
                            Bemerkung = "Remark 2",
                            Beschr = "Description 2",
                            Dimmer = "D2",
                            Eingang = "I2",
                            Fi = "FI-B",
                            Gruppe = "G2",
                            Info = "Info 2",
                            KabelInfo = "Fiber",
                            Leiter = "L2",
                            Raum = "102",
                            Relais = "R2",
                            Sicherung = "S2",
                            SpsPositionImArray = "2",
                            Stockwerk = "First Floor",
                            StockwerkKurz = "FF",
                            Typ = "Type B"
                        },
                        new
                        {
                            ComponentId = 3,
                            Ausgang = "A3",
                            Bemerkung = "Remark 3",
                            Beschr = "Description 3",
                            Dimmer = "D3",
                            Eingang = "I3",
                            Fi = "FI-C",
                            Gruppe = "G3",
                            Info = "Info 3",
                            KabelInfo = "Copper",
                            Leiter = "L3",
                            Raum = "201",
                            Relais = "R3",
                            Sicherung = "S3",
                            SpsPositionImArray = "3",
                            Stockwerk = "Second Floor",
                            StockwerkKurz = "SF",
                            Typ = "Type C"
                        },
                        new
                        {
                            ComponentId = 4,
                            Ausgang = "A4",
                            Bemerkung = "Remark 4",
                            Beschr = "Description 4",
                            Dimmer = "D4",
                            Eingang = "I4",
                            Fi = "FI-D",
                            Gruppe = "G4",
                            Info = "Info 4",
                            KabelInfo = "Fiber",
                            Leiter = "L4",
                            Raum = "202",
                            Relais = "R4",
                            Sicherung = "S4",
                            SpsPositionImArray = "4",
                            Stockwerk = "Second Floor",
                            StockwerkKurz = "SF",
                            Typ = "Type D"
                        },
                        new
                        {
                            ComponentId = 5,
                            Ausgang = "A5",
                            Bemerkung = "Remark 5",
                            Beschr = "Description 5",
                            Dimmer = "D5",
                            Eingang = "I5",
                            Fi = "FI-E",
                            Gruppe = "G5",
                            Info = "Info 5",
                            KabelInfo = "Copper",
                            Leiter = "L5",
                            Raum = "301",
                            Relais = "R5",
                            Sicherung = "S5",
                            SpsPositionImArray = "5",
                            Stockwerk = "Third Floor",
                            StockwerkKurz = "TF",
                            Typ = "Type E"
                        },
                        new
                        {
                            ComponentId = 6,
                            Ausgang = "A6",
                            Bemerkung = "Remark 6",
                            Beschr = "Description 6",
                            Dimmer = "D6",
                            Eingang = "I6",
                            Fi = "FI-F",
                            Gruppe = "G6",
                            Info = "Info 6",
                            KabelInfo = "Fiber",
                            Leiter = "L6",
                            Raum = "302",
                            Relais = "R6",
                            Sicherung = "S6",
                            SpsPositionImArray = "6",
                            Stockwerk = "Third Floor",
                            StockwerkKurz = "TF",
                            Typ = "Type F"
                        },
                        new
                        {
                            ComponentId = 7,
                            Ausgang = "A7",
                            Bemerkung = "Remark 7",
                            Beschr = "Description 7",
                            Dimmer = "D7",
                            Eingang = "I7",
                            Fi = "FI-G",
                            Gruppe = "G7",
                            Info = "Info 7",
                            KabelInfo = "Copper",
                            Leiter = "L7",
                            Raum = "401",
                            Relais = "R7",
                            Sicherung = "S7",
                            SpsPositionImArray = "7",
                            Stockwerk = "Fourth Floor",
                            StockwerkKurz = "FoF",
                            Typ = "Type G"
                        },
                        new
                        {
                            ComponentId = 8,
                            Ausgang = "A8",
                            Bemerkung = "Remark 8",
                            Beschr = "Description 8",
                            Dimmer = "D8",
                            Eingang = "I8",
                            Fi = "FI-H",
                            Gruppe = "G8",
                            Info = "Info 8",
                            KabelInfo = "Fiber",
                            Leiter = "L8",
                            Raum = "402",
                            Relais = "R8",
                            Sicherung = "S8",
                            SpsPositionImArray = "8",
                            Stockwerk = "Fourth Floor",
                            StockwerkKurz = "FoF",
                            Typ = "Type H"
                        },
                        new
                        {
                            ComponentId = 9,
                            Ausgang = "A9",
                            Bemerkung = "Remark 9",
                            Beschr = "Description 9",
                            Dimmer = "D9",
                            Eingang = "I9",
                            Fi = "FI-I",
                            Gruppe = "G9",
                            Info = "Info 9",
                            KabelInfo = "Copper",
                            Leiter = "L9",
                            Raum = "501",
                            Relais = "R9",
                            Sicherung = "S9",
                            SpsPositionImArray = "9",
                            Stockwerk = "Fifth Floor",
                            StockwerkKurz = "FiF",
                            Typ = "Type I"
                        },
                        new
                        {
                            ComponentId = 10,
                            Ausgang = "A10",
                            Bemerkung = "Remark 10",
                            Beschr = "Description 10",
                            Dimmer = "D10",
                            Eingang = "I10",
                            Fi = "FI-J",
                            Gruppe = "G10",
                            Info = "Info 10",
                            KabelInfo = "Fiber",
                            Leiter = "L10",
                            Raum = "502",
                            Relais = "R10",
                            Sicherung = "S10",
                            SpsPositionImArray = "10",
                            Stockwerk = "Fifth Floor",
                            StockwerkKurz = "FiF",
                            Typ = "Type J"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
